name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

    
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The path to the file you want to upload.
        asset_path: ./target/release/zed.exe
        # probably you will need to change it, but most likely you are
        # uploading a binary file
        asset_content_type: application/octet-stream
