name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: add target1
      run: rustup target add x86_64-pc-windows-gnu
    - name: add target2
      run: rustup toolchain install stable-x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --release --target x86_64-pc-windows-gnu
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The path to the file you want to upload.
        asset_path: ./target/release/zed.exe
        # probably you will need to change it, but most likely you are
        # uploading a binary file
        asset_content_type: application/octet-stream
